export const questionsData = [
    {
        question: 'What is the purpose of HTML?',
        answer: 0,
        options: [
        'To structure content on the web',
        'To style web pages',
        'To define server-side logic',
        'To create dynamic animations',
        'None of the above',
        ],
        selected: null,
    },
    {
        question: 'Which tag is used for creating a hyperlink in HTML?',
        answer: 0,
        options: ['<a>', '<link>', '<href>', '<anchor>', 'None of the above'],
        selected: null,
    },
    {
        question: 'Which HTML tag is used for creating an unordered list?',
        answer: 1,
        options: ['<ol>', '<ul>', '<li>', '<list>', 'None of the above'],
        selected: null,
    },
    {
        question: 'What does HTML stand for?',
        answer: 0,
        options: [
        'Hypertext Markup Language',
        'Hyperlink and Text Markup Language',
        'High-Level Text Management Language',
        'Home Tool Markup Language',
        'None of the above',
        ],
        selected: null,
    },
    {
        question: 'In jQuery, what does the following code do?',
        code: '$("button").click(function() { alert("Button Clicked!"); })',
        answer: 0,
        options: [
            'Attaches a click event handler to all button elements to show an alert',
            'Hides all button elements on the page',
            'Removes all button elements from the DOM',
            'Changes the text content of all button elements',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'Which CSS property is used in a style attribute to specify a background color?',
        answer: 4,
        options: ['color', 'bgcolor', 'background', 'backgroundColor', 'background-color'],
        selected: null,
    },
    {
        question: 'Identify the property that is *not* used to define the style of a text?',
        answer: 3,
        options: ['font-weight', 'font-style', 'color', 'font-align', 'font-size'],
        selected: null,
    },
    {
        question: 'Which CSS style definition will *not* work?',
        answer: 2,
        options: [
            '.class1 {font-weight:bold;}',
            '.class2 {font-size:12px}',
            '.class3 {colour:red;}',
            '.class4 {text-align:center;}',
            'None of the above, they all work',
        ],
        selected: null,
    },
    {
        question: 'What HTML class is used for creating a responsive navigation bar?',
        answer: 1,
        options: ['.navbar', '.responsive', '.nav', '.nav-responsive', '.nav-bar'],
        selected: null,
    },
    {
        question: 'What is Bootstrap?',
        answer: 0,
        options: [
            'A popular front-end framework',
            'A JavaScript library',
            'A programming language',
            'A type of coffee',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'Which of these languages is mostly used server-side (back-end)?',
        answer: 3,
        options: ['HTML', 'JavaScript', 'CSS', 'Perl', 'None of these'],
        selected: null,
    },
    {
        question: 'Which web server is often used with PHP and MySQL?',
        answer: 0,
        options: ['Apache', 'Nginx', 'IIS', 'Tomcat', 'LiteSpeed'],
        selected: null,
    },
    {
        question: 'What movie format (extension) is not compatible with HTML5?',
        answer: 2,
        options: ['OGG', 'MP4', 'MKV', 'WebM', 'All are compatible'],
        selected: null,
    },
    {
        question: 'In the following jQuery statement, what is supposed to go into the part indicated as C?',
        answer: 1,
        options: [
            'the selector',
            'the speed',
            'the opacity',
            'the callback',
            'something else',
        ],
        selected: null,
    },
    {
        question: 'What does SVG stand for?',
        answer: 0,
        options: [
            'Scalable Vector Graphics',
            'Structured View Graphics',
            'Static Visual Graphics',
            'Server Variable Graphics',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'How do you select all elements with the class "example" in jQuery?',
        answer: 1,
        options: [
            '$("example")',
            '$(".example")',
            '$("#example")',
            '$("div.example")',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'Which HTML tag is used to embed an SVG image?',
        answer: 3,
        options: ['<img>', '<picture>', '<svg>', '<embed>', '<vector>'],
        selected: null,
    },
    {
        question: 'What statement links an external Perl subroutine file to the main program?',
        answer: 2,
        options: ['link', 'sublink', 'require', 'include', 'subroutine'],
        selected: null,
    },
    {
        question: 'In the following jQuery statement, what is supposed to go into the part indicated as C?',
        code: '$(A).animate(B,C,D);',
        answer: 2,
        options: [
            'the selector',
            'the speed',
            'the opacity',
            'the callback',
            'something else',
        ],
        selected: null,
    },
    {
        question: 'What does CGI stand for in the context of Perl?',
        answer: 0,
        options: [
            'Common Gateway Interface',
            'Computer Graphics Interface',
            'Code Generation Infrastructure',
            'Command-line Graphical Interface',
            'None of the above',
        ],
        selected: null,
    },    
    {
        question: 'What PHP statement is used to write to a file?',
        answer: 3,
        options: ['response.write', 'fprintf', 'writef', 'fwrite', 'print'],
        selected: null,
    },
    {
        question: 'What is the string concatenation operator in Perl?',
        answer: 0,
        options: ['.', '+', 'strcat', 'cat', '&'],
        selected: null,
    },
    {
        question: 'What ASP function is used to retrieve information from a form submitted with the GET method?',
        answer: 1,
        options: ['request.form', 'request.querystring', 'request.post', '$_GET', 'request.get'],
        selected: null,
    },
    {
        question: 'What keyword is used to define a function in Ruby?',
        answer: 1,
        options: ['func', 'def', 'yield', 'define', 'function'],
        selected: null,
    },
    {
        question: 'What does the acronym DOM stands for (in the Web programming context)?',
        answer: 0,
        options: [
            'Document Object Model',
            'Document Oriented Model',
            'Document Object Management',
            'Digital Object Model',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'What is the purpose of the "let" keyword in JavaScript?',
        answer: 1,
        options: [
            'To declare a constant variable',
            'To declare a block-scoped variable',
            'To define a function',
            'To include an external script',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'What does the following Ruby code snippet do?',
        code: 'numbers = [1, 2, 3, 4, 5]\nsum = 0\nnumbers.each { |num| sum += num }\nputs sum',
        answer: 2,
        options: [
            'Calculates the product of all numbers in the array',
            'Counts the total number of elements in the array',
            'Calculates the sum of all numbers in the array',
            'Prints each element of the array to the console',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'What keyword is used to define a function in JavaScript?',
        answer: 3,
        options: ['function', 'def', 'define', 'func', 'method'],
        selected: null,
    },
    {
        question: 'Which HTML tag is used for creating a table?',
        answer: 2,
        options: ['<table>', '<grid>', '<tab>', '<tb>', '<tbl>'],
        selected: null,
    },
    {
        question: 'In SEO, what does the term "backlink" refer to?',
        answer: 4,
        options: [
            'A broken hyperlink',
            'An internal link within the same website',
            'A link to a previous version of the page',
            'A link to a competitor\'s website',
            'A link from another website to your website',
        ],
        selected: null,
    },
    {
        question: 'Which HTML color code would give a shade of gray?',
        answer: 3,
        options: ['#ffffcc', '#ccccff', '#ffcc44', '#666666', '#669966'],
        selected: null,
    },
    {
        question: 'What is the correct tag sequence to specify an audio file in HTML5?',
        answer: 1,
        options: [
            '<source src="mysong.mp3" type="audio/mpeg" />',
            '<audio src="mysong.mp3" type="audio/mpeg" />',
            '<video src="mysong.mp3" type="audio/mpeg" />',
            '<mpeg src="mysong.mp3" type="audio/mpeg" />',
            '<play src="mysong.mp3" type="audio/mpeg" />',
        ],
        selected: null,
    },
    {
        question: 'What is the output of the following PHP code?',
        code: '$s2 = substr_replace("toronto", "o", -2, 2); echo $s2;',
        answer: 2,
        options: [ 'toronto', 't2r2nt2', 'torono', 'oronto', 'torooto' ],
        selected: null,
    },
    {
        question: 'What does XPath stand for?',
        answer: 0,
        options: [
            'XML Path Language',
            'Extensible HyperText Markup Language',
            'XML Syntax and Parsing',
            'Xtensible Hyperlink and Text Markup Language',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'What is the correct declaration for an array with 50 cells in ASP?',
        answer: 2,
        options: [
            'dim array [50]',
            'array (49)',
            'dim array(50)',
            'dim array (49)',
            'dim array [49]',
        ],
        selected: null,
    },
    {
    question: 'What is the result of the following in Perl?',
    code: '$x = "The color property is used to set the color of the text"; @a = split (/ color /,$x); print $a[1];',
    answer: 2,
    options: [ 'The', 'color', 'property is used to set the', 'of the text', 'None of the above' ],
    selected: null,
    },
    {
        question: 'What is printed out after the following Python statements?',
        code: 'list = [1, 2, 3, 4, 5, 6, 7]; print list[1:5]',
        answer: 2,
        options: [ '1 2 3 4 5', '1 2 3 4 5 6', '[2,3,4,5]', '2 3 4 5', 'None of these' ],
        selected: null,
    },
    {
        question: 'What is the output of the following Perl code?',
        code: '$x = 5; $y = 10; print $x + $y;',
        answer: 4,
        options: [ '5', '10', '15', '50', 'None of the above' ],
        selected: null,
    },
    {
        question: 'What is the correct way to comment out multiple lines in PHP?',
        answer: 0,
        options: [
            '/* This is a comment */',
            '// This is a comment',
            '# This is a comment',
            '-- This is a comment',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'In JavaScript, what is the purpose of the `typeof` operator?',
        answer: 2,
        options: [
            'To create a new variable',
            'To check if a variable is defined',
            'To determine the data type of a variable',
            'To perform type conversion',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'What is the primary purpose of XML?',
        answer: 0,
        options: [
            'To define a set of rules for encoding documents in a format that is both human-readable and machine-readable',
            'To execute programs on a web server',
            'To style web pages',
            'To create dynamic animations',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'In PHP, what is the purpose of the `echo` statement?',
        answer: 0,
        options: [
            'To output one or more strings',
            'To execute a loop',
            'To declare a variable',
            'To include an external file',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'What does the acronym SQL stand for?',
        answer: 2,
        options: [
            'Structured Text and Query Language',
            'Systematic Testing and Quality Language',
            'Structured Query Language',
            'Systemic Task and Quality Language',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'How to insert data into a MySQL table?',
        answer: 2,
        options: [
            'INSERT INTO table VALUES (data);',
            'ADD INTO table (data) VALUES;',
            'INSERT INTO table (column1, column2, ...) VALUES (value1, value2, ...);',
            'ADD DATA table VALUES (value);',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'How to alter a MySQL table?',
        answer: 3,
        options: [
            'ALTER table MODIFY column datatype;',
            'CHANGE table COLUMN column datatype;',
            'UPDATE table SET column = datatype;',
            'ALTER TABLE table MODIFY COLUMN column datatype;',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'What is the default name of Apache\'s directory-level config file on a shared environment?',
        answer: 3,
        options: [
            '.config',
            '.settings',
            '.htconfig',
            '.htaccess',
            '.apacheconfig',
        ],
        selected: null,
    },
    {
        question: 'What is the result of x in this JavaScript code?',
        code: 'let x = 5 + "3"; console.log(x);',
        answer: 3,
        options: [
            '8',
            '15',
            '53',
            'Error',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'In jQuery, what does the following code do?',
        code: '$("div").animate({left: "250px"}, "slow");',
        answer: 0,
        options: [
            'Animates the left position of all div elements to 250 pixels with a slow duration',
            'Fades out all div elements on the page',
            'Appends a new div element to the page',
            'Changes the background color of all div elements',
            'None of the above',
        ],
        selected: null,
    },
    {
        question: 'What does a media query do in responsive web design?',
        answer: 1,
        options: ['Define font sizes', 'Adapt styles based on device characteristics', 'Create interactive animations', 'Manage server-side logic', 'Control database queries'],
        selected: null,
    },
    {
        question: 'In Bootstrap, which class is used to create a responsive, fixed-width container?',
        answer: 4,
        options: ['.container-fluid', '.container-fixed', '.container-responsive', '.fixed-container', '.container'],
        selected: null,
    }
];  